---
# Download a WAR File to the Tomcat webapps directory to be deployed
- name: Download a WAR File to the Tomcat webapps directory to be deployed
  maven_artifact:
    group_id: in.shan5a6
    artifact_id: myweb
    extension: war
    version: "{{version}}"
    username: "{{nexus_user}}"
    password: "{{nexus_password}}"    
    repository_url: 'http://{{nexusserverip}}/repository/java-releases/'
    dest: "/tmp/"
    owner: "{{service_account}}"
    group: "{{service_account}}" 
  register: artifact_name

- name:  Copy the artifact to the target folder
  copy:
    src: "{{artifact_name.dest}}"
    dest: "{{tomcat_path}}/webapps/app.war"
    remote_src: yes
  register: deployment_status

- name: Restart tomcat services
  systemd:
    name: tomcat-service
    state: restarted
  when: deployment_status.changed

